7.0 devel
TieredMemDB/TieredMemDB pull request #29
Opened 2022-06-30 10:12 UTC by maciekpac

2022-07-07 14:35 UTC, bratpiorka requested changes
> Reviewed 24 of 24 files at r1, 8 of 8 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)

___
*[`src/adlist.h` line 81 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-N6O2xUT9pZlBN5MFt68:-N6O2xUT9pZlBN5MFt69:b-kauf1d) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/1100e49c45b1faf45ac22313e29c96a2c8cf50b2/src/adlist.h#L81)):*
> ```objc
> list *listAddNodeHead(list *list, void *value);
> list *listAddNodeHeadDRAM(list *list, void *value);
> list *listAddNodeTail(list *list, void *value);
> ```

why there is no tail DRAM version?


<!-- Sent from Reviewable.io -->

2022-07-07 14:44 UTC, bratpiorka approved these changes
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-07-07 17:00 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: all files reviewed, 1 unresolved discussion (waiting on @bratpiorka and @PatKamin)

___
*[`src/adlist.h` line 81 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-N6O2xUT9pZlBN5MFt68:-N6OaAR12Sdv0VsTEuCL:b-ahw0fb) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/1100e49c45b1faf45ac22313e29c96a2c8cf50b2/src/adlist.h#L81)):*
<details><summary><i>Previously, bratpiorka (Rafał Rudnicki) wrote…</i></summary><blockquote>

why there is no tail DRAM version?
</blockquote></details>

I suppose this was not needed, maybe we only need to add DRAM nodes at head ?

6.2.5-devel does not have this function either;

If we want to investigate it, I think we should set up a separate task/do it later - I'm only porting code from old branches here


<!-- Sent from Reviewable.io -->

2022-07-08 07:07 UTC, bratpiorka approved these changes
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)

___
*[`src/adlist.h` line 81 at r1](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-N6O2xUT9pZlBN5MFt68:-N6RccwdA3JeJWCWE1z1:b-4obeei) ([raw file](https://github.com/tieredmemdb/tieredmemdb/blob/1100e49c45b1faf45ac22313e29c96a2c8cf50b2/src/adlist.h#L81)):*
<details><summary><i>Previously, maciekpac wrote…</i></summary><blockquote>

I suppose this was not needed, maybe we only need to add DRAM nodes at head ?

6.2.5-devel does not have this function either;

If we want to investigate it, I think we should set up a separate task/do it later - I'm only porting code from old branches here
</blockquote></details>

ok, agree - I will add separate task for that


<!-- Sent from Reviewable.io -->

2022-07-11 07:25 UTC, bratpiorka approved these changes
> Reviewed 2 of 15 files at r4, 3 of 8 files at r5, 11 of 11 files at r6, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PatKamin)



<!-- Sent from Reviewable.io -->

2022-07-11 08:47 UTC, PatKamin requested changes
> Reviewed 1 of 24 files at r1, 1 of 11 files at r6, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: all files reviewed, 1 unresolved discussion (waiting on @maciekpac)

___
*[`-- commits` line 4 at r13](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-N6gR94D4icfWZ3oAbgE):*
v1.14.0


<!-- Sent from Reviewable.io -->

2022-07-11 08:58 UTC, PatKamin commented on .github/workflows/ci.yml
> +    - name: Build TieredMemDB
Please, merge this commit with the one that introduces memkind in github actions. No reason for keeping a fix commit with the commit introducing changes in the very same PR.

2022-07-11 12:33 UTC, maciekpac reviewed
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: all files reviewed, 1 unresolved discussion (waiting on @PatKamin)

___
*[`-- commits` line 4 at r13](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-N6gR94D4icfWZ3oAbgE):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

v1.14.0
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 12:34 UTC, PatKamin reviewed
> Reviewed 5 of 35 files at r14.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: 0 of 43 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-07-11 13:24 UTC, maciekpac reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-:-N6hQgur967QDk79K7YR:bb6un1j)* status: 0 of 43 files reviewed, all discussions resolved (waiting on @bratpiorka and @PatKamin)



<!-- Sent from Reviewable.io -->

2022-07-11 13:35 UTC, bratpiorka approved these changes
> Reviewed 15 of 24 files at r21, 28 of 28 files at r33, 11 of 11 files at r34, 12 of 12 files at r35, 10 of 10 files at r36, 11 of 11 files at r37, 18 of 18 files at r38, 10 of 10 files at r39, 11 of 11 files at r40, 3 of 3 files at r41, 1 of 1 files at r42, 10 of 10 files at r43, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-07-13 10:14 UTC, PatKamin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 24 files at r21, 28 of 28 files at r33.
> *[Reviewable](https://reviewable.io/reviews/tieredmemdb/tieredmemdb/29#-:-N6r2SXM2GJcczNCTsBg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maciekpac)



<!-- Sent from Reviewable.io -->

2022-07-13 10:15 UTC, merged